apiVersion: apps/v1
kind: Deployment
metadata:
  name: spammer-1
  labels:
    app: spammer-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spammer-1
  template:
    metadata:
      labels:
        app: spammer-1
    spec:
      containers:
        - name: spammer-1
          image: spammer
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: SPAMMER_PORT
              value: "80"
            - name: SPAMMER_COUNT
              value: "1024"
            - name: SPAMMER_SIZE
              value: "16384"
            - name: SPAMMER_DELAY_MS
              value: "50"

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: spammer-1
  name: spammer-1
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 30001
  selector:
    app: spammer-1
  sessionAffinity: None
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spammer-2
  labels:
    app: spammer-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spammer-2
  template:
    metadata:
      labels:
        app: spammer-2
    spec:
      containers:
        - name: spammer-2
          image: spammer
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: SPAMMER_PORT
              value: "80"
            - name: SPAMMER_COUNT
              value: "1024"
            - name: SPAMMER_SIZE
              value: "16384"
            - name: SPAMMER_DELAY_MS
              value: "50"

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: spammer-2
  name: spammer-2
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 30002
  selector:
    app: spammer-2
  sessionAffinity: None
  type: NodePort
